# Generated by Django 4.1.7 on 2023-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=40)),
                ('apellido_estudiante', models.CharField(max_length=40)),
                ('email_estudiante', models.CharField(max_length=60)),
            ],
        ),
    ]
