# Generated by Django 4.1.7 on 2023-03-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='email_estudiante',
            field=models.EmailField(max_length=254),
        ),
    ]
