# Generated by Django 4.1.7 on 2023-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEstudiantes', '0002_alter_estudiante_email_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profe', models.CharField(max_length=40)),
                ('apellido_profe', models.CharField(max_length=40)),
                ('email_profe', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=30)),
            ],
        ),
    ]
